apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: site-projects
bases:
- ../workload
images:
- name: devlaunchers/site-projects
  newName: devlaunchers/site-projects
  newTag: 1.1.0 # {"$imagepolicy": "site-projects:site-projects:tag"}
