apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: site-projects
bases:
- ../workload
images:
- name: devlaunchers/site-projects
  newName: devlaunchers/site-projects
  newTag: 1.1.4 # {"$imagepolicy": "site-projects:site-projects:tag"}
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    namespace: site-projects
    name: site-projects
    labels:
      app: site-projects
  spec:
    template:
      spec:
        containers:
        - name: site-projects
          resources:
            limits:
              cpu: 0.01
              memory: 200Mi
            requests:
              cpu: 0.01
              memory: 200Mi
        nodeSelector:
          type: virtual-kubelet
        tolerations:
        - key: virtual-kubelet.io/provider
          operator: Exists
        - key: azure.com/aci
          effect: NoSchedule